const state={patient:null,entries:[],filter:'all'},toast=document.querySelector('#toast'),role=document.querySelector('#role');
const say=t=>{toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)},headers=()=>({'X-Actor-Role':role.value,'X-Actor-Id':`${role.value}_demo`,'X-Clinic-Id':'clinic_demo','Content-Type':'application/json'}),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}const kind=e=>({clinician_sections:'Clinical',staff_notes:'Staff',ai_scribed:'AI summary',patient_facing:'Patient-facing'})[e.section]||e.section;
async function loadPatients(){const ps=await api('/api/patients'),box=patientList;box.innerHTML=ps.length?ps.map(p=>`<button class="patient-row ${state.patient?.id===p.id?'current':''}" data-id="${p.id}" data-name="${esc(p.display_label)}">${esc(p.display_label)}</button>`).join(''):'<p class="small-note">No patients yet.</p>';box.querySelectorAll('.patient-row').forEach(b=>b.onclick=()=>selectPatient({id:b.dataset.id,display_label:b.dataset.name}));if(!state.patient&&ps[0])await selectPatient(ps[0])}
async function selectPatient(p){state.patient=p;patientName.textContent=p.display_label;heading.textContent=`${p.display_label} · Care context`;patientMeta.textContent=`Patient page · ${p.id}`;await loadTimeline();await loadPatients()}
async function loadTimeline(){if(!state.patient)return;state.entries=await api(`/api/patients/${state.patient.id}/timeline`);renderTimeline();renderGlance()}
function renderGlance(){const rows=state.entries.filter(e=>e.open_action||e.risk_level>0).slice(0,3);glanceRows.innerHTML=rows.length?`<div class="facts">${rows.map(e=>`<div><small>${e.open_action?'Open action':'Risk'} · ${kind(e)}</small><strong>${esc(e.content.slice(0,48))}</strong><button class="jump" data-id="${e.id}">View source →</button></div>`).join('')}</div>`:'<div class="empty">No open actions or flagged risks.</div>';document.querySelectorAll('.jump').forEach(b=>b.onclick=()=>document.querySelector(`#entry-${b.dataset.id}`)?.scrollIntoView({behavior:'smooth',block:'center'}))}
function renderTimeline(){const es=state.filter==='all'?state.entries:state.entries.filter(e=>e.section===state.filter);timeline.innerHTML=es.length?es.map(e=>`<article id="entry-${e.id}"><span class="dot blue"></span><div class="meta"><span class="system">${e.author_role==='system'?'✦ AI':esc(e.author_id.slice(0,2))}</span><b>${esc(e.author_id)}</b><small>${kind(e)} · ${esc(e.entry_type)}</small><time>${new Date(e.created_at).toLocaleString('en-US')}</time><mark>Entry ID: ${e.id}<br>v${e.version}</mark></div><div class="text ${e.section==='clinician_sections'?'editable':''}" ${e.section==='clinician_sections'?'contenteditable="true"':''}>${esc(e.content)}</div><div class="actions"><button class="save" data-id="${e.id}" data-v="${e.version}">Save edit</button><button class="comments-btn" data-id="${e.id}">Comments</button><button class="versions" data-id="${e.id}">Versions</button></div><div class="comments" id="comments-${e.id}"></div><div class="history" id="history-${e.id}"></div></article>`).join(''):'<div class="empty">No records yet.</div>'}
function configureTypes(){entryType.innerHTML=(clinicalKind.value==='nurse'?[['nurse_daily','Nurse daily note'],['nurse_patient_consult','Nurse–patient consult'],['nurse_other','Nurse other']]:[['doctor_daily','Doctor daily note'],['doctor_patient_consult','Doctor–patient consult'],['doctor_other','Doctor other']]).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}
createPatient.onclick=()=>patientDialog.showModal();addEntry.onclick=()=>state.patient?entryDialog.showModal():say('Create a patient first');savePatient.onclick=async e=>{e.preventDefault();const p=await api('/api/patients',{method:'POST',body:JSON.stringify({display_label:patientInput.value})});patientDialog.close();await selectPatient(p)};saveEntry.onclick=async e=>{e.preventDefault();await api(`/api/patients/${state.patient.id}/entries`,{method:'POST',body:JSON.stringify({section:section.value,entry_type:entryType.value,content:entryContent.value,open_action:openAction.checked})});entryDialog.close();entryContent.value='';await loadTimeline()};document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .selected').classList.remove('selected');b.classList.add('selected');state.filter=b.dataset.filter;renderTimeline()});refreshPatients.onclick=loadPatients;role.onchange=()=>{state.patient=null;loadPatients()};loadPatients().catch(e=>say(e.message));
